exports.teamList = {
  "count": 48,
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 103984,
      "name": "MOAI",
      "description": "",
      "org": 4819,
      "avatar": 358,
      "vendor": null,
      "created_at": "2021-09-10T13:56:46.840211",
      "parent": null,
      "path": "103984",
      "ancestors": [
        "MOAI"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 6,
      "unnested_users": 6,
      "depth": "inherit"
    },
    {
      "id": 104678,
      "name": "Lealta",
      "description": "The dream team crafting Lealta Health",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2021-10-05T07:56:35.257938",
      "parent": null,
      "path": "104678",
      "ancestors": [
        "Lealta"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 6,
      "unnested_users": 6,
      "depth": "inherit"
    },
    {
      "id": 11099,
      "name": "Medidata",
      "description": null,
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2019-03-24T10:44:00.611712",
      "parent": null,
      "path": "11099",
      "ancestors": [
        "Medidata"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 4,
      "unnested_users": 4,
      "depth": "atomic"
    },
    {
      "id": 11519,
      "name": "Mortgage Squirrel",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2019-04-04T10:46:18.174060",
      "parent": null,
      "path": "11519",
      "ancestors": [
        "Mortgage Squirrel"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 3,
      "unnested_users": 3,
      "depth": "inherit"
    },
    {
      "id": 11527,
      "name": "Front End",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2019-04-04T20:33:20.786111",
      "parent": null,
      "path": "11527",
      "ancestors": [
        "Front End"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 7,
      "unnested_users": 7,
      "depth": "inherit"
    },
    {
      "id": 11943,
      "name": "Kandu",
      "description": "Kandu team",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2019-04-17T09:42:45.925255",
      "parent": null,
      "path": "11943",
      "ancestors": [
        "Kandu"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 7,
      "unnested_users": 7,
      "depth": "inherit"
    },
    {
      "id": 11944,
      "name": "Sipp",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2019-04-17T10:08:28.226692",
      "parent": null,
      "path": "11944",
      "ancestors": [
        "Sipp"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 2,
      "unnested_users": 2,
      "depth": "inherit"
    },
    {
      "id": 11945,
      "name": "ExperienceThis",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2019-04-17T10:12:48.323197",
      "parent": null,
      "path": "11945",
      "ancestors": [
        "ExperienceThis"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 3,
      "unnested_users": 3,
      "depth": "inherit"
    },
    {
      "id": 11946,
      "name": "European Recycling Platform",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2019-04-17T10:16:33.796278",
      "parent": null,
      "path": "11946",
      "ancestors": [
        "European Recycling Platform"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 1,
      "unnested_users": 1,
      "depth": "inherit"
    },
    {
      "id": 11948,
      "name": "ICQ",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2019-04-17T10:27:38.568153",
      "parent": null,
      "path": "11948",
      "ancestors": [
        "ICQ"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 2,
      "unnested_users": 2,
      "depth": "inherit"
    },
    {
      "id": 11950,
      "name": "StudyRocket",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2019-04-17T10:51:07.929224",
      "parent": null,
      "path": "11950",
      "ancestors": [
        "StudyRocket"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 7,
      "unnested_users": 7,
      "depth": "inherit"
    },
    {
      "id": 11951,
      "name": "Pegasus",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2019-04-17T10:52:33.759204",
      "parent": null,
      "path": "11951",
      "ancestors": [
        "Pegasus"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 4,
      "unnested_users": 4,
      "depth": "inherit"
    },
    {
      "id": 12157,
      "name": "All Users",
      "description": "All users, for reference",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2019-04-29T15:31:21.474856",
      "parent": null,
      "path": "12157",
      "ancestors": [
        "All Users"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 32,
      "unnested_users": 32,
      "depth": "inherit"
    },
    {
      "id": 12719,
      "name": "Collarbone",
      "description": "Collarbone Project",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2019-05-21T13:55:35.481226",
      "parent": null,
      "path": "12719",
      "ancestors": [
        "Collarbone"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 2,
      "unnested_users": 2,
      "depth": "inherit"
    },
    {
      "id": 13585,
      "name": "Bangkok",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2019-06-10T04:17:28.414775",
      "parent": null,
      "path": "13585",
      "ancestors": [
        "Bangkok"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 36,
      "unnested_users": 36,
      "depth": "inherit"
    },
    {
      "id": 13586,
      "name": "Cape Town",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2019-06-10T04:17:38.350740",
      "parent": null,
      "path": "13586",
      "ancestors": [
        "Cape Town"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 26,
      "unnested_users": 26,
      "depth": "inherit"
    },
    {
      "id": 14499,
      "name": "Nomad",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2019-07-21T13:51:10.061717",
      "parent": null,
      "path": "14499",
      "ancestors": [
        "Nomad"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 3,
      "unnested_users": 3,
      "depth": "inherit"
    },
    {
      "id": 14502,
      "name": "Brighton",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2019-07-22T11:45:26.607215",
      "parent": null,
      "path": "14502",
      "ancestors": [
        "Brighton"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 4,
      "unnested_users": 4,
      "depth": "inherit"
    },
    {
      "id": 15603,
      "name": "Kidadl",
      "description": "Kidadl gitflow",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2019-08-13T10:58:09.167414",
      "parent": null,
      "path": "15603",
      "ancestors": [
        "Kidadl"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 5,
      "unnested_users": 5,
      "depth": "inherit"
    },
    {
      "id": 20272,
      "name": "Hostology",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2020-01-28T12:30:35.048520",
      "parent": null,
      "path": "20272",
      "ancestors": [
        "Hostology"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 7,
      "unnested_users": 7,
      "depth": "inherit"
    },
    {
      "id": 20273,
      "name": "Kikapay",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2020-01-28T12:42:44.734111",
      "parent": null,
      "path": "20273",
      "ancestors": [
        "Kikapay"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 5,
      "unnested_users": 5,
      "depth": "inherit"
    },
    {
      "id": 30114,
      "name": "WeGive",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2020-05-26T04:39:08.740483",
      "parent": null,
      "path": "30114",
      "ancestors": [
        "WeGive"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 6,
      "unnested_users": 6,
      "depth": "inherit"
    },
    {
      "id": 71718,
      "name": "EMSOL",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2020-10-19T17:30:19.117760",
      "parent": null,
      "path": "71718",
      "ancestors": [
        "EMSOL"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 9,
      "unnested_users": 9,
      "depth": "inherit"
    },
    {
      "id": 94621,
      "name": "Guru",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2021-02-04T10:38:53.801152",
      "parent": null,
      "path": "94621",
      "ancestors": [
        "Guru"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 4,
      "unnested_users": 4,
      "depth": "inherit"
    },
    {
      "id": 94626,
      "name": "Stoa",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2021-02-04T11:20:04.301358",
      "parent": null,
      "path": "94626",
      "ancestors": [
        "Stoa"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 2,
      "unnested_users": 2,
      "depth": "inherit"
    },
    {
      "id": 95611,
      "name": "EVO",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2021-02-10T10:22:36.705250",
      "parent": null,
      "path": "95611",
      "ancestors": [
        "EVO"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 13,
      "unnested_users": 13,
      "depth": "inherit"
    },
    {
      "id": 95612,
      "name": "Primis",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2021-02-10T10:24:39.802894",
      "parent": null,
      "path": "95612",
      "ancestors": [
        "Primis"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 7,
      "unnested_users": 7,
      "depth": "inherit"
    },
    {
      "id": 96703,
      "name": "SMC",
      "description": "SMC Project",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2021-03-16T12:05:28.265942",
      "parent": null,
      "path": "96703",
      "ancestors": [
        "SMC"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 4,
      "unnested_users": 4,
      "depth": "inherit"
    },
    {
      "id": 98774,
      "name": "Lalu",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2021-04-23T08:17:34.598744",
      "parent": null,
      "path": "98774",
      "ancestors": [
        "Lalu"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 11,
      "unnested_users": 11,
      "depth": "inherit"
    },
    {
      "id": 99383,
      "name": "Dell Card Game",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2021-04-29T09:25:42.657504",
      "parent": null,
      "path": "99383",
      "ancestors": [
        "Dell Card Game"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 7,
      "unnested_users": 7,
      "depth": "inherit"
    },
    {
      "id": 110238,
      "name": "WECtec",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2022-05-16T12:10:59.287456",
      "parent": null,
      "path": "110238",
      "ancestors": [
        "WECtec"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 3,
      "unnested_users": 3,
      "depth": "inherit"
    },
    {
      "id": 113706,
      "name": "Bloss",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2022-08-23T09:54:37.126022",
      "parent": null,
      "path": "113706",
      "ancestors": [
        "Bloss"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 2,
      "unnested_users": 2,
      "depth": "atomic"
    },
    {
      "id": 115804,
      "name": "Fluint",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2022-10-26T21:17:30.052527",
      "parent": null,
      "path": "115804",
      "ancestors": [
        "Fluint"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 3,
      "unnested_users": 3,
      "depth": "inherit"
    },
    {
      "id": 116623,
      "name": "ekko",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2022-11-11T14:26:23.030296",
      "parent": null,
      "path": "116623",
      "ancestors": [
        "ekko"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 6,
      "unnested_users": 6,
      "depth": "atomic"
    },
    {
      "id": 118520,
      "name": "Acolyte",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2023-01-09T15:42:17.567349",
      "parent": null,
      "path": "118520",
      "ancestors": [
        "Acolyte"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 9,
      "unnested_users": 9,
      "depth": "inherit"
    },
    {
      "id": 131073,
      "name": "EA inclusion",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2023-06-06T12:40:38.335677",
      "parent": null,
      "path": "131073",
      "ancestors": [
        "EA inclusion"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 6,
      "unnested_users": 6,
      "depth": "inherit"
    },
    {
      "id": 150504,
      "name": "EnviroEconomy",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2023-10-27T14:03:58.719045",
      "parent": null,
      "path": "150504",
      "ancestors": [
        "EnviroEconomy"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 2,
      "unnested_users": 2,
      "depth": "inherit"
    },
    {
      "id": 150505,
      "name": "EA People Ltd",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2023-10-27T14:18:23.000218",
      "parent": null,
      "path": "150505",
      "ancestors": [
        "EA People Ltd"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 13,
      "unnested_users": 13,
      "depth": "inherit"
    },
    {
      "id": 150506,
      "name": "Geronimo",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2023-10-27T14:21:35.495337",
      "parent": null,
      "path": "150506",
      "ancestors": [
        "Geronimo"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 5,
      "unnested_users": 5,
      "depth": "inherit"
    },
    {
      "id": 150507,
      "name": "QR",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2023-10-27T14:23:31.678279",
      "parent": null,
      "path": "150507",
      "ancestors": [
        "QR"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 7,
      "unnested_users": 7,
      "depth": "inherit"
    },
    {
      "id": 150508,
      "name": "Lucra Payments",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2023-10-27T14:25:11.687077",
      "parent": null,
      "path": "150508",
      "ancestors": [
        "Lucra Payments"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 1,
      "unnested_users": 1,
      "depth": "inherit"
    },
    {
      "id": 150509,
      "name": "Boardly",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2023-10-27T14:26:17.337943",
      "parent": null,
      "path": "150509",
      "ancestors": [
        "Boardly"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 8,
      "unnested_users": 8,
      "depth": "inherit"
    },
    {
      "id": 150510,
      "name": "The Event Academy",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2023-10-27T14:28:14.811116",
      "parent": null,
      "path": "150510",
      "ancestors": [
        "The Event Academy"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 2,
      "unnested_users": 2,
      "depth": "inherit"
    },
    {
      "id": 150512,
      "name": "Survey Shack",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2023-10-27T14:35:40.275492",
      "parent": null,
      "path": "150512",
      "ancestors": [
        "Survey Shack"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 1,
      "unnested_users": 1,
      "depth": "inherit"
    },
    {
      "id": 113606,
      "name": "Muov",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2022-08-16T04:55:01.701184",
      "parent": null,
      "path": "113606",
      "ancestors": [
        "Muov"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 10,
      "unnested_users": 10,
      "depth": "inherit"
    },
    {
      "id": 120762,
      "name": "RMW",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2023-02-13T15:16:27.337149",
      "parent": null,
      "path": "120762",
      "ancestors": [
        "RMW"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 8,
      "unnested_users": 8,
      "depth": "inherit"
    },
    {
      "id": 127981,
      "name": "Taos",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2023-03-27T13:21:38.234945",
      "parent": null,
      "path": "127981",
      "ancestors": [
        "Taos"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 5,
      "unnested_users": 5,
      "depth": "inherit"
    },
    {
      "id": 150511,
      "name": "Kyozo",
      "description": "",
      "org": 4819,
      "avatar": null,
      "vendor": null,
      "created_at": "2023-10-27T14:33:21.362680",
      "parent": null,
      "path": "150511",
      "ancestors": [
        "Kyozo"
      ],
      "visibility": "SHOW",
      "team_level": 1,
      "inherited_depth": "atomic",
      "nested_teams": 0,
      "all_users": 7,
      "unnested_users": 7,
      "depth": "inherit"
    }
  ]
};

exports.singleTeam = exports.teamList.results
  .find(({ id }) => id === 95611);